name: CoreSettings
version: 1.0.0
main: com.core.settings.CoreSettings
api-version: 1.20
authors: [Henry]
description: A highly customizable player settings GUI.

commands:
  settings:
    description: Opens the settings GUI or reloads config.
    usage: /settings [reload]

permissions:
  coresettings.use:
    description: Allows opening the settings GUI.
    default: true
  coresettings.fly:
    description: Allows toggling flight mode.
    default: op
  coresettings.admin:
    description: Allows reloading the plugin config.
    default: op
